// 보완 v2 화면 확인용(배포 주소).
import { chromium } from "playwright-core";
const BASE = process.argv[2] ?? "https://dasel-weld.vercel.app";
const browser = await chromium.launch({ channel: "chrome", args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, locale: "ko-KR" });
await ctx.addInitScript(() => { try { for (const k of ["dasel_tour_v1", "dasel_tour_sim_v1", "dasel_tour_list_v1"]) localStorage.setItem(k, "done"); } catch {} });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", (e) => errs.push(String(e).slice(0, 160)));
const txt = (sel) => page.locator(sel).first().innerText().then((t) => t.replace(/\s+/g, " ").trim()).catch(() => null);
const out = {};
await page.goto(`${BASE}/?b=121902`);
await page.waitForSelector("#WF2");
await page.waitForTimeout(4000);
out.roof_ai = await txt("#TXT-ROOF-AI");
await page.goto(BASE);
await page.waitForSelector("#CRD-00");
await page.waitForTimeout(3000);
out.banner = await txt("#CRD-00");
await page.goto(`${BASE}/sim`);
await page.waitForSelector("#TBL-01");
out.sim_total = await txt("#TBL-01 tbody tr:last-child");
await page.goto(`${BASE}/method`);
const body = await page.locator("body").innerText();
out.method = ["ML 교차검증", "지붕 이용률 판독", "재사용 배터리 집계", "3,905"].map((k) => [k, body.includes(k)]);
out.dash = (body.match(/—/g) ?? []).length;
out.errs = errs;
await browser.close();
console.log(JSON.stringify(out, null, 1));
